[Service]
Name="app-core"
Port = 8888
StartupMsg = 'This is the local Environment StartupMsg.'


[Logg]
Level = 'DEBUG'
File = '/logs/app-core.log'


[Clients]
  [Clients.Mongo]
  Protocol = 'mongodb'
  Host = 'localhost'
  Port = 27017
  Username = ''
  Password = ''
  [Clients.Mongo.More]
  Database='card'
  Collection_Todo='todo'

