[Service]
Name="app-core"
Port = 8888
StartupMsg = 'This is the docker Environment StartupMsg.'


[Logg]
Level = 'DEBUG'
File = '/logs/app-core.log'


[Clients]
  [Clients.Mongo]
  Protocol = 'mongodb'
  Host = 'mongo'
  Port = 27017
  Username = ''
  Password = ''
