definitions:
  models.InfoUpdate:
    properties:
      description:
        type: string
      name:
        type: string
    required:
    - description
    - name
    type: object
info:
  contact: {}
  description: This is a sample service server.
  title: Swagger Example API
  version: "1.0"
paths:
  /service/api/v1/info:
    get:
      consumes:
      - application/json
      description: Get info API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get info API
      tags:
      - infos
    put:
      description: put info API service name
      parameters:
      - description: InfoUpdate
        in: body
        name: InfoUpdate
        required: true
        schema:
          $ref: '#/definitions/models.InfoUpdate'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: put info API
      tags:
      - infos
swagger: "2.0"
