info:
  contact: {}
  description: This is a sample server celler server.
  title: Swagger Example API
  version: "1.0"
paths:
  /service/api/v1/info:
    get:
      consumes:
      - application/json
      description: Get info API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get info API
      tags:
      - infos
swagger: "2.0"
